# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output publish
  name: runDotnetPublish
  displayName: 'dotnet publish $(buildConfiguration)'

- task: ArchiveFiles@2
  displayName: 'Create Archive: publish/application.zip'
  inputs:
    rootFolderOrFile: 'publish/' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: 'publish/application.zip' 
    replaceExistingArchive: true

- task: PublishPipelineArtifact@0
  displayName: 'Publish pipeline artifact - application.zip'
  inputs:
    artifactName: 'application'
    targetPath: 'publish/application.zip'
    